# TODO: Docker image for NIDS server
FROM python:3.11-slim
WORKDIR /app
COPY server/ ./server/
COPY shared/ ./shared/
RUN pip install -r server/requirements.txt
EXPOSE 5000
CMD ["python", "server/app.py"]
