version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: nids_postgres
    environment:
      POSTGRES_USER: nids_user
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: nids_db
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:7
    container_name: nids_redis
    ports:
      - "6379:6379"
    restart: always